Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'integration/**/*'
    - '*.gemspec'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'integration/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
    - 'integration/**/*'
